(define (problem emergency) (:domain exit)
(:objects
exit_b center exit_a crossroad_1 crossroad_2 bog_and_ide crossroad_3 crossroad_4 crossroad_5 crossroad_6 crossroad_7 crossroad_8 toilets crossroad_13 crossroad_14 crossroad_15 paw_sko smart_eyes exit_c nails_gallery bella_donna crossroad_16 big_hall crossroad_17 exit_d crossroad_18 synoptik change  - nodes
exit_b-crossroad_1 center-crossroad_2 center-crossroad_3 center-crossroad_5 center-crossroad_8 center-crossroad_7 exit_a-crossroad_4 exit_a-crossroad_6 crossroad_1-exit_b crossroad_1-crossroad_4 crossroad_1-crossroad_2 crossroad_2-crossroad_1 crossroad_2-center crossroad_2-toilets bog_and_ide-crossroad_3 crossroad_3-center crossroad_3-bog_and_ide crossroad_3-crossroad_4 crossroad_4-crossroad_1 crossroad_4-crossroad_3 crossroad_4-exit_a crossroad_5-center crossroad_5-crossroad_6 crossroad_6-crossroad_5 crossroad_6-crossroad_13 crossroad_6-exit_a crossroad_7-center crossroad_7-crossroad_17 crossroad_8-center crossroad_8-crossroad_14 toilets-crossroad_2 crossroad_13-crossroad_6 crossroad_13-smart_eyes crossroad_13-big_hall crossroad_14-crossroad_8 crossroad_14-paw_sko crossroad_14-crossroad_15 crossroad_15-crossroad_14 crossroad_15-nails_gallery crossroad_15-bella_donna crossroad_15-crossroad_16 paw_sko-crossroad_14 smart_eyes-crossroad_13 exit_c-crossroad_16 nails_gallery-crossroad_15 bella_donna-crossroad_15 crossroad_16-crossroad_15 crossroad_16-exit_c big_hall-crossroad_13 big_hall-exit_d big_hall-crossroad_18 crossroad_17-crossroad_7 crossroad_17-crossroad_18 crossroad_17-change exit_d-big_hall crossroad_18-big_hall crossroad_18-crossroad_17 crossroad_18-synoptik synoptik-crossroad_18 change-crossroad_17 exit_b-exit_b center-center exit_a-exit_a crossroad_1-crossroad_1 crossroad_2-crossroad_2 bog_and_ide-bog_and_ide crossroad_3-crossroad_3 crossroad_4-crossroad_4 crossroad_5-crossroad_5 crossroad_6-crossroad_6 crossroad_7-crossroad_7 crossroad_8-crossroad_8 toilets-toilets crossroad_13-crossroad_13 crossroad_14-crossroad_14 crossroad_15-crossroad_15 paw_sko-paw_sko smart_eyes-smart_eyes exit_c-exit_c nails_gallery-nails_gallery bella_donna-bella_donna crossroad_16-crossroad_16 big_hall-big_hall crossroad_17-crossroad_17 exit_d-exit_d crossroad_18-crossroad_18 synoptik-synoptik change-change  - edges
center0 center1 center2 center3 center4 center5 center6 center7 center8 center9 center10 center11 center12 center13 center14 center15 center16 center17 center18 center19 center20 center21 center22 center23 center24 center25 center26 center27 center28 center29 crossroad_20 crossroad_21 crossroad_22 crossroad_23 crossroad_24 crossroad_25 crossroad_26 crossroad_27 crossroad_28 crossroad_29 crossroad_210 crossroad_211 crossroad_212 crossroad_213 crossroad_214 crossroad_215 crossroad_216 crossroad_217 crossroad_218 crossroad_219 bog_and_ide0 bog_and_ide1 bog_and_ide2 bog_and_ide3 bog_and_ide4 bog_and_ide5 bog_and_ide6 bog_and_ide7 bog_and_ide8 bog_and_ide9 bog_and_ide10 bog_and_ide11 bog_and_ide12 bog_and_ide13 bog_and_ide14 bog_and_ide15 bog_and_ide16 bog_and_ide17 bog_and_ide18 bog_and_ide19 crossroad_40 crossroad_41 crossroad_42 crossroad_43 crossroad_44 crossroad_45 crossroad_46 crossroad_47 crossroad_48 crossroad_49 crossroad_140 crossroad_141 crossroad_142 crossroad_143 crossroad_144 crossroad_145 crossroad_146 crossroad_147 crossroad_148 crossroad_149 nails_gallery0 nails_gallery1 nails_gallery2 nails_gallery3 nails_gallery4 nails_gallery5 nails_gallery6 nails_gallery7 nails_gallery8 nails_gallery9 bella_donna0 bella_donna1 bella_donna2 bella_donna3 bella_donna4 bella_donna5 bella_donna6 bella_donna7 bella_donna8 bella_donna9 virtual  - agents
to from - modes
)

(:init
(= (road_cost) 0)(mode from)(to-mode to)(from-mode from)(available virtual)(last-agent virtual)
 (first-agent center0)
(= (counter exit_b-crossroad_1) 0)
(= (counter center-crossroad_2) 0)
(= (counter center-crossroad_3) 0)
(= (counter center-crossroad_5) 0)
(= (counter center-crossroad_8) 0)
(= (counter center-crossroad_7) 0)
(= (counter exit_a-crossroad_4) 0)
(= (counter exit_a-crossroad_6) 0)
(= (counter crossroad_1-exit_b) 0)
(= (counter crossroad_1-crossroad_4) 0)
(= (counter crossroad_1-crossroad_2) 0)
(= (counter crossroad_2-crossroad_1) 0)
(= (counter crossroad_2-center) 0)
(= (counter crossroad_2-toilets) 0)
(= (counter bog_and_ide-crossroad_3) 0)
(= (counter crossroad_3-center) 0)
(= (counter crossroad_3-bog_and_ide) 0)
(= (counter crossroad_3-crossroad_4) 0)
(= (counter crossroad_4-crossroad_1) 0)
(= (counter crossroad_4-crossroad_3) 0)
(= (counter crossroad_4-exit_a) 0)
(= (counter crossroad_5-center) 0)
(= (counter crossroad_5-crossroad_6) 0)
(= (counter crossroad_6-crossroad_5) 0)
(= (counter crossroad_6-crossroad_13) 0)
(= (counter crossroad_6-exit_a) 0)
(= (counter crossroad_7-center) 0)
(= (counter crossroad_7-crossroad_17) 0)
(= (counter crossroad_8-center) 0)
(= (counter crossroad_8-crossroad_14) 0)
(= (counter toilets-crossroad_2) 0)
(= (counter crossroad_13-crossroad_6) 0)
(= (counter crossroad_13-smart_eyes) 0)
(= (counter crossroad_13-big_hall) 0)
(= (counter crossroad_14-crossroad_8) 0)
(= (counter crossroad_14-paw_sko) 0)
(= (counter crossroad_14-crossroad_15) 0)
(= (counter crossroad_15-crossroad_14) 0)
(= (counter crossroad_15-nails_gallery) 0)
(= (counter crossroad_15-bella_donna) 0)
(= (counter crossroad_15-crossroad_16) 0)
(= (counter paw_sko-crossroad_14) 0)
(= (counter smart_eyes-crossroad_13) 0)
(= (counter exit_c-crossroad_16) 0)
(= (counter nails_gallery-crossroad_15) 0)
(= (counter bella_donna-crossroad_15) 0)
(= (counter crossroad_16-crossroad_15) 0)
(= (counter crossroad_16-exit_c) 0)
(= (counter big_hall-crossroad_13) 0)
(= (counter big_hall-exit_d) 0)
(= (counter big_hall-crossroad_18) 0)
(= (counter crossroad_17-crossroad_7) 0)
(= (counter crossroad_17-crossroad_18) 0)
(= (counter crossroad_17-change) 0)
(= (counter exit_d-big_hall) 0)
(= (counter crossroad_18-big_hall) 0)
(= (counter crossroad_18-crossroad_17) 0)
(= (counter crossroad_18-synoptik) 0)
(= (counter synoptik-crossroad_18) 0)
(= (counter change-crossroad_17) 0)
(= (counter exit_b-exit_b) 0)
(= (counter center-center) 0)
(= (counter exit_a-exit_a) 0)
(= (counter crossroad_1-crossroad_1) 0)
(= (counter crossroad_2-crossroad_2) 0)
(= (counter bog_and_ide-bog_and_ide) 0)
(= (counter crossroad_3-crossroad_3) 0)
(= (counter crossroad_4-crossroad_4) 0)
(= (counter crossroad_5-crossroad_5) 0)
(= (counter crossroad_6-crossroad_6) 0)
(= (counter crossroad_7-crossroad_7) 0)
(= (counter crossroad_8-crossroad_8) 0)
(= (counter toilets-toilets) 0)
(= (counter crossroad_13-crossroad_13) 0)
(= (counter crossroad_14-crossroad_14) 0)
(= (counter crossroad_15-crossroad_15) 0)
(= (counter paw_sko-paw_sko) 0)
(= (counter smart_eyes-smart_eyes) 0)
(= (counter exit_c-exit_c) 0)
(= (counter nails_gallery-nails_gallery) 0)
(= (counter bella_donna-bella_donna) 0)
(= (counter crossroad_16-crossroad_16) 0)
(= (counter big_hall-big_hall) 0)
(= (counter crossroad_17-crossroad_17) 0)
(= (counter exit_d-exit_d) 0)
(= (counter crossroad_18-crossroad_18) 0)
(= (counter synoptik-synoptik) 0)
(= (counter change-change) 0)

 (next-agent center0 center1)
 (next-agent center1 center2)
 (next-agent center2 center3)
 (next-agent center3 center4)
 (next-agent center4 center5)
 (next-agent center5 center6)
 (next-agent center6 center7)
 (next-agent center7 center8)
 (next-agent center8 center9)
 (next-agent center9 center10)
 (next-agent center10 center11)
 (next-agent center11 center12)
 (next-agent center12 center13)
 (next-agent center13 center14)
 (next-agent center14 center15)
 (next-agent center15 center16)
 (next-agent center16 center17)
 (next-agent center17 center18)
 (next-agent center18 center19)
 (next-agent center19 center20)
 (next-agent center20 center21)
 (next-agent center21 center22)
 (next-agent center22 center23)
 (next-agent center23 center24)
 (next-agent center24 center25)
 (next-agent center25 center26)
 (next-agent center26 center27)
 (next-agent center27 center28)
 (next-agent center28 center29)
 (next-agent center29 crossroad_20)
 (next-agent crossroad_20 crossroad_21)
 (next-agent crossroad_21 crossroad_22)
 (next-agent crossroad_22 crossroad_23)
 (next-agent crossroad_23 crossroad_24)
 (next-agent crossroad_24 crossroad_25)
 (next-agent crossroad_25 crossroad_26)
 (next-agent crossroad_26 crossroad_27)
 (next-agent crossroad_27 crossroad_28)
 (next-agent crossroad_28 crossroad_29)
 (next-agent crossroad_29 crossroad_210)
 (next-agent crossroad_210 crossroad_211)
 (next-agent crossroad_211 crossroad_212)
 (next-agent crossroad_212 crossroad_213)
 (next-agent crossroad_213 crossroad_214)
 (next-agent crossroad_214 crossroad_215)
 (next-agent crossroad_215 crossroad_216)
 (next-agent crossroad_216 crossroad_217)
 (next-agent crossroad_217 crossroad_218)
 (next-agent crossroad_218 crossroad_219)
 (next-agent crossroad_219 bog_and_ide0)
 (next-agent bog_and_ide0 bog_and_ide1)
 (next-agent bog_and_ide1 bog_and_ide2)
 (next-agent bog_and_ide2 bog_and_ide3)
 (next-agent bog_and_ide3 bog_and_ide4)
 (next-agent bog_and_ide4 bog_and_ide5)
 (next-agent bog_and_ide5 bog_and_ide6)
 (next-agent bog_and_ide6 bog_and_ide7)
 (next-agent bog_and_ide7 bog_and_ide8)
 (next-agent bog_and_ide8 bog_and_ide9)
 (next-agent bog_and_ide9 bog_and_ide10)
 (next-agent bog_and_ide10 bog_and_ide11)
 (next-agent bog_and_ide11 bog_and_ide12)
 (next-agent bog_and_ide12 bog_and_ide13)
 (next-agent bog_and_ide13 bog_and_ide14)
 (next-agent bog_and_ide14 bog_and_ide15)
 (next-agent bog_and_ide15 bog_and_ide16)
 (next-agent bog_and_ide16 bog_and_ide17)
 (next-agent bog_and_ide17 bog_and_ide18)
 (next-agent bog_and_ide18 bog_and_ide19)
 (next-agent bog_and_ide19 crossroad_40)
 (next-agent crossroad_40 crossroad_41)
 (next-agent crossroad_41 crossroad_42)
 (next-agent crossroad_42 crossroad_43)
 (next-agent crossroad_43 crossroad_44)
 (next-agent crossroad_44 crossroad_45)
 (next-agent crossroad_45 crossroad_46)
 (next-agent crossroad_46 crossroad_47)
 (next-agent crossroad_47 crossroad_48)
 (next-agent crossroad_48 crossroad_49)
 (next-agent crossroad_49 crossroad_140)
 (next-agent crossroad_140 crossroad_141)
 (next-agent crossroad_141 crossroad_142)
 (next-agent crossroad_142 crossroad_143)
 (next-agent crossroad_143 crossroad_144)
 (next-agent crossroad_144 crossroad_145)
 (next-agent crossroad_145 crossroad_146)
 (next-agent crossroad_146 crossroad_147)
 (next-agent crossroad_147 crossroad_148)
 (next-agent crossroad_148 crossroad_149)
 (next-agent crossroad_149 nails_gallery0)
 (next-agent nails_gallery0 nails_gallery1)
 (next-agent nails_gallery1 nails_gallery2)
 (next-agent nails_gallery2 nails_gallery3)
 (next-agent nails_gallery3 nails_gallery4)
 (next-agent nails_gallery4 nails_gallery5)
 (next-agent nails_gallery5 nails_gallery6)
 (next-agent nails_gallery6 nails_gallery7)
 (next-agent nails_gallery7 nails_gallery8)
 (next-agent nails_gallery8 nails_gallery9)
 (next-agent nails_gallery9 bella_donna0)
 (next-agent bella_donna0 bella_donna1)
 (next-agent bella_donna1 bella_donna2)
 (next-agent bella_donna2 bella_donna3)
 (next-agent bella_donna3 bella_donna4)
 (next-agent bella_donna4 bella_donna5)
 (next-agent bella_donna5 bella_donna6)
 (next-agent bella_donna6 bella_donna7)
 (next-agent bella_donna7 bella_donna8)
 (next-agent bella_donna8 bella_donna9)
 (next-agent bella_donna9 virtual)
(entry exit_b exit_b-exit_b)(leave exit_b-exit_b exit_b)
(entry center center-center)(leave center-center center)
(entry exit_a exit_a-exit_a)(leave exit_a-exit_a exit_a)
(entry crossroad_1 crossroad_1-crossroad_1)(leave crossroad_1-crossroad_1 crossroad_1)
(entry crossroad_2 crossroad_2-crossroad_2)(leave crossroad_2-crossroad_2 crossroad_2)
(entry bog_and_ide bog_and_ide-bog_and_ide)(leave bog_and_ide-bog_and_ide bog_and_ide)
(entry crossroad_3 crossroad_3-crossroad_3)(leave crossroad_3-crossroad_3 crossroad_3)
(entry crossroad_4 crossroad_4-crossroad_4)(leave crossroad_4-crossroad_4 crossroad_4)
(entry crossroad_5 crossroad_5-crossroad_5)(leave crossroad_5-crossroad_5 crossroad_5)
(entry crossroad_6 crossroad_6-crossroad_6)(leave crossroad_6-crossroad_6 crossroad_6)
(entry crossroad_7 crossroad_7-crossroad_7)(leave crossroad_7-crossroad_7 crossroad_7)
(entry crossroad_8 crossroad_8-crossroad_8)(leave crossroad_8-crossroad_8 crossroad_8)
(entry toilets toilets-toilets)(leave toilets-toilets toilets)
(entry crossroad_13 crossroad_13-crossroad_13)(leave crossroad_13-crossroad_13 crossroad_13)
(entry crossroad_14 crossroad_14-crossroad_14)(leave crossroad_14-crossroad_14 crossroad_14)
(entry crossroad_15 crossroad_15-crossroad_15)(leave crossroad_15-crossroad_15 crossroad_15)
(entry paw_sko paw_sko-paw_sko)(leave paw_sko-paw_sko paw_sko)
(entry smart_eyes smart_eyes-smart_eyes)(leave smart_eyes-smart_eyes smart_eyes)
(entry exit_c exit_c-exit_c)(leave exit_c-exit_c exit_c)
(entry nails_gallery nails_gallery-nails_gallery)(leave nails_gallery-nails_gallery nails_gallery)
(entry bella_donna bella_donna-bella_donna)(leave bella_donna-bella_donna bella_donna)
(entry crossroad_16 crossroad_16-crossroad_16)(leave crossroad_16-crossroad_16 crossroad_16)
(entry big_hall big_hall-big_hall)(leave big_hall-big_hall big_hall)
(entry crossroad_17 crossroad_17-crossroad_17)(leave crossroad_17-crossroad_17 crossroad_17)
(entry exit_d exit_d-exit_d)(leave exit_d-exit_d exit_d)
(entry crossroad_18 crossroad_18-crossroad_18)(leave crossroad_18-crossroad_18 crossroad_18)
(entry synoptik synoptik-synoptik)(leave synoptik-synoptik synoptik)
(entry change change-change)(leave change-change change)
(entry exit_b exit_b-crossroad_1)(leave exit_b-crossroad_1 crossroad_1)
(entry center center-crossroad_2)(leave center-crossroad_2 crossroad_2)
(entry center center-crossroad_3)(leave center-crossroad_3 crossroad_3)
(entry center center-crossroad_5)(leave center-crossroad_5 crossroad_5)
(entry center center-crossroad_8)(leave center-crossroad_8 crossroad_8)
(entry center center-crossroad_7)(leave center-crossroad_7 crossroad_7)
(entry exit_a exit_a-crossroad_4)(leave exit_a-crossroad_4 crossroad_4)
(entry exit_a exit_a-crossroad_6)(leave exit_a-crossroad_6 crossroad_6)
(entry crossroad_1 crossroad_1-exit_b)(leave crossroad_1-exit_b exit_b)
(entry crossroad_1 crossroad_1-crossroad_4)(leave crossroad_1-crossroad_4 crossroad_4)
(entry crossroad_1 crossroad_1-crossroad_2)(leave crossroad_1-crossroad_2 crossroad_2)
(entry crossroad_2 crossroad_2-crossroad_1)(leave crossroad_2-crossroad_1 crossroad_1)
(entry crossroad_2 crossroad_2-center)(leave crossroad_2-center center)
(entry crossroad_2 crossroad_2-toilets)(leave crossroad_2-toilets toilets)
(entry bog_and_ide bog_and_ide-crossroad_3)(leave bog_and_ide-crossroad_3 crossroad_3)
(entry crossroad_3 crossroad_3-center)(leave crossroad_3-center center)
(entry crossroad_3 crossroad_3-bog_and_ide)(leave crossroad_3-bog_and_ide bog_and_ide)
(entry crossroad_3 crossroad_3-crossroad_4)(leave crossroad_3-crossroad_4 crossroad_4)
(entry crossroad_4 crossroad_4-crossroad_1)(leave crossroad_4-crossroad_1 crossroad_1)
(entry crossroad_4 crossroad_4-crossroad_3)(leave crossroad_4-crossroad_3 crossroad_3)
(entry crossroad_4 crossroad_4-exit_a)(leave crossroad_4-exit_a exit_a)
(entry crossroad_5 crossroad_5-center)(leave crossroad_5-center center)
(entry crossroad_5 crossroad_5-crossroad_6)(leave crossroad_5-crossroad_6 crossroad_6)
(entry crossroad_6 crossroad_6-crossroad_5)(leave crossroad_6-crossroad_5 crossroad_5)
(entry crossroad_6 crossroad_6-crossroad_13)(leave crossroad_6-crossroad_13 crossroad_13)
(entry crossroad_6 crossroad_6-exit_a)(leave crossroad_6-exit_a exit_a)
(entry crossroad_7 crossroad_7-center)(leave crossroad_7-center center)
(entry crossroad_7 crossroad_7-crossroad_17)(leave crossroad_7-crossroad_17 crossroad_17)
(entry crossroad_8 crossroad_8-center)(leave crossroad_8-center center)
(entry crossroad_8 crossroad_8-crossroad_14)(leave crossroad_8-crossroad_14 crossroad_14)
(entry toilets toilets-crossroad_2)(leave toilets-crossroad_2 crossroad_2)
(entry crossroad_13 crossroad_13-crossroad_6)(leave crossroad_13-crossroad_6 crossroad_6)
(entry crossroad_13 crossroad_13-smart_eyes)(leave crossroad_13-smart_eyes smart_eyes)
(entry crossroad_13 crossroad_13-big_hall)(leave crossroad_13-big_hall big_hall)
(entry crossroad_14 crossroad_14-crossroad_8)(leave crossroad_14-crossroad_8 crossroad_8)
(entry crossroad_14 crossroad_14-paw_sko)(leave crossroad_14-paw_sko paw_sko)
(entry crossroad_14 crossroad_14-crossroad_15)(leave crossroad_14-crossroad_15 crossroad_15)
(entry crossroad_15 crossroad_15-crossroad_14)(leave crossroad_15-crossroad_14 crossroad_14)
(entry crossroad_15 crossroad_15-nails_gallery)(leave crossroad_15-nails_gallery nails_gallery)
(entry crossroad_15 crossroad_15-bella_donna)(leave crossroad_15-bella_donna bella_donna)
(entry crossroad_15 crossroad_15-crossroad_16)(leave crossroad_15-crossroad_16 crossroad_16)
(entry paw_sko paw_sko-crossroad_14)(leave paw_sko-crossroad_14 crossroad_14)
(entry smart_eyes smart_eyes-crossroad_13)(leave smart_eyes-crossroad_13 crossroad_13)
(entry exit_c exit_c-crossroad_16)(leave exit_c-crossroad_16 crossroad_16)
(entry nails_gallery nails_gallery-crossroad_15)(leave nails_gallery-crossroad_15 crossroad_15)
(entry bella_donna bella_donna-crossroad_15)(leave bella_donna-crossroad_15 crossroad_15)
(entry crossroad_16 crossroad_16-crossroad_15)(leave crossroad_16-crossroad_15 crossroad_15)
(entry crossroad_16 crossroad_16-exit_c)(leave crossroad_16-exit_c exit_c)
(entry big_hall big_hall-crossroad_13)(leave big_hall-crossroad_13 crossroad_13)
(entry big_hall big_hall-exit_d)(leave big_hall-exit_d exit_d)
(entry big_hall big_hall-crossroad_18)(leave big_hall-crossroad_18 crossroad_18)
(entry crossroad_17 crossroad_17-crossroad_7)(leave crossroad_17-crossroad_7 crossroad_7)
(entry crossroad_17 crossroad_17-crossroad_18)(leave crossroad_17-crossroad_18 crossroad_18)
(entry crossroad_17 crossroad_17-change)(leave crossroad_17-change change)
(entry exit_d exit_d-big_hall)(leave exit_d-big_hall big_hall)
(entry crossroad_18 crossroad_18-big_hall)(leave crossroad_18-big_hall big_hall)
(entry crossroad_18 crossroad_18-crossroad_17)(leave crossroad_18-crossroad_17 crossroad_17)
(entry crossroad_18 crossroad_18-synoptik)(leave crossroad_18-synoptik synoptik)
(entry synoptik synoptik-crossroad_18)(leave synoptik-crossroad_18 crossroad_18)
(entry change change-crossroad_17)(leave change-crossroad_17 crossroad_17)
(= (road_risk exit_b-crossroad_1) 0)
(= (road_risk center-crossroad_2) 0)
(= (road_risk center-crossroad_3) 0)
(= (road_risk center-crossroad_5) 0)
(= (road_risk center-crossroad_8) 0)
(= (road_risk center-crossroad_7) 0)
(= (road_risk exit_a-crossroad_4) 0)
(= (road_risk exit_a-crossroad_6) 0)
(= (road_risk crossroad_1-exit_b) 0)
(= (road_risk crossroad_1-crossroad_4) 100)
(= (road_risk crossroad_1-crossroad_2) 0)
(= (road_risk crossroad_2-crossroad_1) 0)
(= (road_risk crossroad_2-center) 0)
(= (road_risk crossroad_2-toilets) 0)
(= (road_risk bog_and_ide-crossroad_3) 0)
(= (road_risk crossroad_3-center) 0)
(= (road_risk crossroad_3-bog_and_ide) 0)
(= (road_risk crossroad_3-crossroad_4) 100)
(= (road_risk crossroad_4-crossroad_1) 100)
(= (road_risk crossroad_4-crossroad_3) 100)
(= (road_risk crossroad_4-exit_a) 0)
(= (road_risk crossroad_5-center) 0)
(= (road_risk crossroad_5-crossroad_6) 80)
(= (road_risk crossroad_6-crossroad_5) 80)
(= (road_risk crossroad_6-crossroad_13) 0)
(= (road_risk crossroad_6-exit_a) 0)
(= (road_risk crossroad_7-center) 0)
(= (road_risk crossroad_7-crossroad_17) 0)
(= (road_risk crossroad_8-center) 0)
(= (road_risk crossroad_8-crossroad_14) 0)
(= (road_risk toilets-crossroad_2) 0)
(= (road_risk crossroad_13-crossroad_6) 0)
(= (road_risk crossroad_13-smart_eyes) 0)
(= (road_risk crossroad_13-big_hall) 0)
(= (road_risk crossroad_14-crossroad_8) 0)
(= (road_risk crossroad_14-paw_sko) 0)
(= (road_risk crossroad_14-crossroad_15) 0)
(= (road_risk crossroad_15-crossroad_14) 0)
(= (road_risk crossroad_15-nails_gallery) 0)
(= (road_risk crossroad_15-bella_donna) 0)
(= (road_risk crossroad_15-crossroad_16) 0)
(= (road_risk paw_sko-crossroad_14) 0)
(= (road_risk smart_eyes-crossroad_13) 0)
(= (road_risk exit_c-crossroad_16) 0)
(= (road_risk nails_gallery-crossroad_15) 0)
(= (road_risk bella_donna-crossroad_15) 0)
(= (road_risk crossroad_16-crossroad_15) 0)
(= (road_risk crossroad_16-exit_c) 0)
(= (road_risk big_hall-crossroad_13) 0)
(= (road_risk big_hall-exit_d) 0)
(= (road_risk big_hall-crossroad_18) 0)
(= (road_risk crossroad_17-crossroad_7) 0)
(= (road_risk crossroad_17-crossroad_18) 0)
(= (road_risk crossroad_17-change) 0)
(= (road_risk exit_d-big_hall) 0)
(= (road_risk crossroad_18-big_hall) 0)
(= (road_risk crossroad_18-crossroad_17) 0)
(= (road_risk crossroad_18-synoptik) 0)
(= (road_risk synoptik-crossroad_18) 0)
(= (road_risk change-crossroad_17) 0)
(= (road_risk exit_b-exit_b) 0)
(= (road_risk center-center) 0)
(= (road_risk exit_a-exit_a) 0)
(= (road_risk crossroad_1-crossroad_1) 0)
(= (road_risk crossroad_2-crossroad_2) 0)
(= (road_risk bog_and_ide-bog_and_ide) 0)
(= (road_risk crossroad_3-crossroad_3) 0)
(= (road_risk crossroad_4-crossroad_4) 0)
(= (road_risk crossroad_5-crossroad_5) 0)
(= (road_risk crossroad_6-crossroad_6) 0)
(= (road_risk crossroad_7-crossroad_7) 0)
(= (road_risk crossroad_8-crossroad_8) 0)
(= (road_risk toilets-toilets) 0)
(= (road_risk crossroad_13-crossroad_13) 0)
(= (road_risk crossroad_14-crossroad_14) 0)
(= (road_risk crossroad_15-crossroad_15) 0)
(= (road_risk paw_sko-paw_sko) 0)
(= (road_risk smart_eyes-smart_eyes) 0)
(= (road_risk exit_c-exit_c) 0)
(= (road_risk nails_gallery-nails_gallery) 0)
(= (road_risk bella_donna-bella_donna) 0)
(= (road_risk crossroad_16-crossroad_16) 0)
(= (road_risk big_hall-big_hall) 0)
(= (road_risk crossroad_17-crossroad_17) 0)
(= (road_risk exit_d-exit_d) 0)
(= (road_risk crossroad_18-crossroad_18) 0)
(= (road_risk synoptik-synoptik) 0)
(= (road_risk change-change) 0)
(at_node center0 center)
(at_node center1 center)
(at_node center2 center)
(at_node center3 center)
(at_node center4 center)
(at_node center5 center)
(at_node center6 center)
(at_node center7 center)
(at_node center8 center)
(at_node center9 center)
(at_node center10 center)
(at_node center11 center)
(at_node center12 center)
(at_node center13 center)
(at_node center14 center)
(at_node center15 center)
(at_node center16 center)
(at_node center17 center)
(at_node center18 center)
(at_node center19 center)
(at_node center20 center)
(at_node center21 center)
(at_node center22 center)
(at_node center23 center)
(at_node center24 center)
(at_node center25 center)
(at_node center26 center)
(at_node center27 center)
(at_node center28 center)
(at_node center29 center)
(at_node crossroad_20 crossroad_2)
(at_node crossroad_21 crossroad_2)
(at_node crossroad_22 crossroad_2)
(at_node crossroad_23 crossroad_2)
(at_node crossroad_24 crossroad_2)
(at_node crossroad_25 crossroad_2)
(at_node crossroad_26 crossroad_2)
(at_node crossroad_27 crossroad_2)
(at_node crossroad_28 crossroad_2)
(at_node crossroad_29 crossroad_2)
(at_node crossroad_210 crossroad_2)
(at_node crossroad_211 crossroad_2)
(at_node crossroad_212 crossroad_2)
(at_node crossroad_213 crossroad_2)
(at_node crossroad_214 crossroad_2)
(at_node crossroad_215 crossroad_2)
(at_node crossroad_216 crossroad_2)
(at_node crossroad_217 crossroad_2)
(at_node crossroad_218 crossroad_2)
(at_node crossroad_219 crossroad_2)
(at_node bog_and_ide0 bog_and_ide)
(at_node bog_and_ide1 bog_and_ide)
(at_node bog_and_ide2 bog_and_ide)
(at_node bog_and_ide3 bog_and_ide)
(at_node bog_and_ide4 bog_and_ide)
(at_node bog_and_ide5 bog_and_ide)
(at_node bog_and_ide6 bog_and_ide)
(at_node bog_and_ide7 bog_and_ide)
(at_node bog_and_ide8 bog_and_ide)
(at_node bog_and_ide9 bog_and_ide)
(at_node bog_and_ide10 bog_and_ide)
(at_node bog_and_ide11 bog_and_ide)
(at_node bog_and_ide12 bog_and_ide)
(at_node bog_and_ide13 bog_and_ide)
(at_node bog_and_ide14 bog_and_ide)
(at_node bog_and_ide15 bog_and_ide)
(at_node bog_and_ide16 bog_and_ide)
(at_node bog_and_ide17 bog_and_ide)
(at_node bog_and_ide18 bog_and_ide)
(at_node bog_and_ide19 bog_and_ide)
(at_node crossroad_40 crossroad_4)
(at_node crossroad_41 crossroad_4)
(at_node crossroad_42 crossroad_4)
(at_node crossroad_43 crossroad_4)
(at_node crossroad_44 crossroad_4)
(at_node crossroad_45 crossroad_4)
(at_node crossroad_46 crossroad_4)
(at_node crossroad_47 crossroad_4)
(at_node crossroad_48 crossroad_4)
(at_node crossroad_49 crossroad_4)
(at_node crossroad_140 crossroad_14)
(at_node crossroad_141 crossroad_14)
(at_node crossroad_142 crossroad_14)
(at_node crossroad_143 crossroad_14)
(at_node crossroad_144 crossroad_14)
(at_node crossroad_145 crossroad_14)
(at_node crossroad_146 crossroad_14)
(at_node crossroad_147 crossroad_14)
(at_node crossroad_148 crossroad_14)
(at_node crossroad_149 crossroad_14)
(at_node nails_gallery0 nails_gallery)
(at_node nails_gallery1 nails_gallery)
(at_node nails_gallery2 nails_gallery)
(at_node nails_gallery3 nails_gallery)
(at_node nails_gallery4 nails_gallery)
(at_node nails_gallery5 nails_gallery)
(at_node nails_gallery6 nails_gallery)
(at_node nails_gallery7 nails_gallery)
(at_node nails_gallery8 nails_gallery)
(at_node nails_gallery9 nails_gallery)
(at_node bella_donna0 bella_donna)
(at_node bella_donna1 bella_donna)
(at_node bella_donna2 bella_donna)
(at_node bella_donna3 bella_donna)
(at_node bella_donna4 bella_donna)
(at_node bella_donna5 bella_donna)
(at_node bella_donna6 bella_donna)
(at_node bella_donna7 bella_donna)
(at_node bella_donna8 bella_donna)
(at_node bella_donna9 bella_donna)
(exit exit_b)
(exit exit_a)
(exit exit_c)
)

(:goal (and
(at-exit center0)
(at-exit center1)
(at-exit center2)
(at-exit center3)
(at-exit center4)
(at-exit center5)
(at-exit center6)
(at-exit center7)
(at-exit center8)
(at-exit center9)
(at-exit center10)
(at-exit center11)
(at-exit center12)
(at-exit center13)
(at-exit center14)
(at-exit center15)
(at-exit center16)
(at-exit center17)
(at-exit center18)
(at-exit center19)
(at-exit center20)
(at-exit center21)
(at-exit center22)
(at-exit center23)
(at-exit center24)
(at-exit center25)
(at-exit center26)
(at-exit center27)
(at-exit center28)
(at-exit center29)
(at-exit crossroad_20)
(at-exit crossroad_21)
(at-exit crossroad_22)
(at-exit crossroad_23)
(at-exit crossroad_24)
(at-exit crossroad_25)
(at-exit crossroad_26)
(at-exit crossroad_27)
(at-exit crossroad_28)
(at-exit crossroad_29)
(at-exit crossroad_210)
(at-exit crossroad_211)
(at-exit crossroad_212)
(at-exit crossroad_213)
(at-exit crossroad_214)
(at-exit crossroad_215)
(at-exit crossroad_216)
(at-exit crossroad_217)
(at-exit crossroad_218)
(at-exit crossroad_219)
(at-exit bog_and_ide0)
(at-exit bog_and_ide1)
(at-exit bog_and_ide2)
(at-exit bog_and_ide3)
(at-exit bog_and_ide4)
(at-exit bog_and_ide5)
(at-exit bog_and_ide6)
(at-exit bog_and_ide7)
(at-exit bog_and_ide8)
(at-exit bog_and_ide9)
(at-exit bog_and_ide10)
(at-exit bog_and_ide11)
(at-exit bog_and_ide12)
(at-exit bog_and_ide13)
(at-exit bog_and_ide14)
(at-exit bog_and_ide15)
(at-exit bog_and_ide16)
(at-exit bog_and_ide17)
(at-exit bog_and_ide18)
(at-exit bog_and_ide19)
(at-exit crossroad_40)
(at-exit crossroad_41)
(at-exit crossroad_42)
(at-exit crossroad_43)
(at-exit crossroad_44)
(at-exit crossroad_45)
(at-exit crossroad_46)
(at-exit crossroad_47)
(at-exit crossroad_48)
(at-exit crossroad_49)
(at-exit crossroad_140)
(at-exit crossroad_141)
(at-exit crossroad_142)
(at-exit crossroad_143)
(at-exit crossroad_144)
(at-exit crossroad_145)
(at-exit crossroad_146)
(at-exit crossroad_147)
(at-exit crossroad_148)
(at-exit crossroad_149)
(at-exit nails_gallery0)
(at-exit nails_gallery1)
(at-exit nails_gallery2)
(at-exit nails_gallery3)
(at-exit nails_gallery4)
(at-exit nails_gallery5)
(at-exit nails_gallery6)
(at-exit nails_gallery7)
(at-exit nails_gallery8)
(at-exit nails_gallery9)
(at-exit bella_donna0)
(at-exit bella_donna1)
(at-exit bella_donna2)
(at-exit bella_donna3)
(at-exit bella_donna4)
(at-exit bella_donna5)
(at-exit bella_donna6)
(at-exit bella_donna7)
(at-exit bella_donna8)
(at-exit bella_donna9)
(forall (?e - edges) (= (counter ?e) 0))))

(:metric minimize (road_cost)))